#cloud-config

groups:
  - docker

users:
  - default
  - name: kenneth
    groups: sudo, docker
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDUFNIUkxH0dK3IfStk6vrE7e2fojWYkVbFAUYQ5XaxNRngbedKP3/PyoQu4z6T4bxZljnimeYNjurt9GvPNgRmaSrQi++0OefVi/CLMA/pUjeCwaVl0ivhlNVjXaLLmqLrQjzvzPs+qDuf0i4D0u2giHTE43QU8OE+nW6PVSGf/APldwptCV8JA/q/DgXge9vXVyEjWo3CXzhvSQceDKCAP4VeDJqrwbBxnaRsk9CVp2X/e83QgLeWiJrHGiUHZA/NhpEE6H12Dr5qAWTp9xHxJR+rhZijuaKNWmww47K5m5twaL+L1NhaTdQE3drQZmxnVBIKbn6JPGZi2n5TO+Pt kenneth@PC-G6-1

package_update: true
package_upgrade: true
packages:
  - nano
  - curl

write_files:
- path: /home/kenneth/guacamole/docker-compose.yml
  content: |
    version: '3.9'
    # networks
    # create a network 'guacamole_net' in mode 'bridged'
    networks:
      guacamole_net:
        driver: bridge
      haproxy_net:
        external: true
    # services
    services:
      # guacd
      guacd:
        container_name: guacamole_backend
        image: guacamole/guacd:latest
        networks:
          guacamole_net:
        restart: always
        volumes:
        - ./drive:/drive:rw
        - ./record:/record:rw
      # postgres
      postgres:
        container_name: guacamole_database
        environment:
          PGDATA: /var/lib/postgresql/data/guacamole
          POSTGRES_DB: guacamole_db
          POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
          POSTGRES_USER: '${POSTGRES_USER}'
        image: postgres:13.4
        networks:
          guacamole_net:
        restart: always
        volumes:
        - ./init:/docker-entrypoint-initdb.d:ro
        - ./data:/var/lib/postgresql/data:rw
      # guacamole
      guacamole:
        container_name: guacamole_frontend
        depends_on:
        - guacd
        - postgres
        environment:
          GUACD_HOSTNAME: guacd
          POSTGRES_DATABASE: guacamole_db
          POSTGRES_HOSTNAME: postgres
          POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
          POSTGRES_USER: '${POSTGRES_USER}'
          POSTGRESQL_AUTO_CREATE_ACCOUNTS: true
        image: guacamole/guacamole:latest
        links:
        - guacd
        networks:
          - guacamole_net
          - haproxy_net
        restart: always
        volumes:
        - ./opt/guacamole/bin/start.sh:/opt/guacamole/bin/start.sh
        - ./drive:/drive:rw

- path: /home/kenneth/guacamole/.env
  content: |
    POSTGRES_PASSWORD='Jh3TPJv7bCQbET'
    POSTGRES_USER='guacamole_db_user'

- path: /home/kenneth/haproxy/docker-compose.yml
  content: |
    version: '3.9'
    services:
      haproxy:
        container_name: haproxy
        image: haproxytech/haproxy-alpine:2.4
        ports:
          - 80:80
          - 443:443
          - 8404:8404
        volumes:
          - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
        networks:
          - haproxy_net
        restart: always
        environment:
          ENDPOINT: '${ENDPOINT}'
    networks:
      haproxy_net:
        name: haproxy_net
        driver: bridge

- path: /home/kenneth/haproxy/haproxy.cfg
  content: |
    global
      stats socket /var/run/api.sock user haproxy group haproxy mode 660 level admin expose-fd listeners
      log stdout format raw local0 info
      maxconn 50000

    resolvers docker_resolver
      nameserver dns 127.0.0.11:53

    defaults
      mode http
      timeout client 10s
      timeout connect 5s
      timeout server 10s
      timeout http-request 10s
      default-server init-addr none
      log global

    frontend stats
      bind *:8404
      stats enable
      stats uri /
      stats refresh 10s

    frontend myfrontend
      mode http
      bind :80
      #bind :443 ssl crt /usr/local/etc/haproxy/certs/traefik.me.pem
      #http-request redirect scheme https code 301 unless { ssl_fc }
      use_backend %[req.hdr(Host),lower]

    backend "${ENDPOINT}"
      server guacamole guacamole:8080 check inter 10s resolvers docker_resolver

- path: /home/kenneth/ip.sh
  content: |
    #!/usr/bin/env sh

    #set -ex

    METHOD="${1:-${METHOD:-cloud}}"
    PUBLIC_IP="${8:-${PUBLIC_IP:-localhost}}"

    publicIpFromInterface() {
      # Couldn't find a valid ipv4 address, using the first IP found on the interfaces as the PUBLIC_IP.
      DEFAULT_INTERFACE="$(ip -4 route list match default | grep -Eo "dev .*" | awk '{print $2}')"
      PUBLIC_IP=$(ip -4 addr sh dev "$DEFAULT_INTERFACE" | grep -w inet | head -n1 | awk '{print $2}' | grep -oE '\b([0-9]{1,3}\.){3}[0-9]{1,3}\b')
      echo "${PUBLIC_IP}"
    }

    publicIpFromMetadata() {
      if cloud-init query vendor-data | grep DigitalOcean >/dev/null; then
        PUBLIC_IP="$(curl -s http://169.254.169.254/metadata/v1/interfaces/public/0/ipv4/address)"
      elif test "$(cloud-init query platform)" = "azure"; then
        PUBLIC_IP="$(curl -H Metadata:true --noproxy '*' 'http://169.254.169.254/metadata/instance/network/interface/0/ipv4/ipAddress/0/publicIpAddress/?api-version=2021-02-01&format=text')"
      fi

      if echo "${PUBLIC_IP}" | grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b"; then
        echo "we got it"
      else
        publicIpFromInterface
      fi
    }

    if test "$METHOD" = "cloud"; then
      publicIpFromMetadata
    fi
  permissions: '0755'

# Configure and deploy Guacamole
runcmd:
  - 'curl -fsSL https://get.docker.com -o get-docker.sh'
  - |
    sh get-docker.sh | grep -qE "ERROR: Unsupported distribution 'rocky'|ERROR: Unsupported distribution 'almalinux'" && sudo dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo && sudo dnf -y install docker-ce docker-ce-cli containerd.io docker-compose-plugin
  - 'systemctl start docker'
  - 'systemctl enable docker'
  - 'mkdir -p /home/kenneth/guacamole/opt/guacamole/bin/'
  - 'curl -fsSL https://raw.githubusercontent.com/apache/guacamole-client/master/guacamole-docker/bin/start.sh -o /home/kenneth/guacamole/opt/guacamole/bin/start.sh'
  - 'chmod +x /home/kenneth/guacamole/opt/guacamole/bin/start.sh'
  - 'mkdir /home/kenneth/guacamole/init >/dev/null 2>&1'
  - 'chmod -R +x /home/kenneth/guacamole/init'
  - 'docker run --rm guacamole/guacamole /opt/guacamole/bin/initdb.sh --postgres > /home/kenneth/guacamole/init/initdb.sql'
  - 'PUBLIC_IP="$(/home/kenneth/ip.sh | grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b")"; echo ENDPOINT="${PUBLIC_IP}.traefik.me" | tee /home/kenneth/haproxy/.env'
  - 'chown -R kenneth:kenneth /home/kenneth/'
  - 'docker compose -f /home/kenneth/haproxy/docker-compose.yml up -d && docker compose -f /home/kenneth/guacamole/docker-compose.yml up -d'